version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CLIENT_ID="155612"
      - CLIENT_SECRET="7cd0b1dd7c81c3755da428082a3228182542886b"

  nginx:
    image: nginx:latest
    ports:
      - "8042:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static_html:/usr/share/nginx/html:ro
    depends_on:
      - app